// ReSharper disable InconsistentNaming

using System;

namespace Erinn.Roslyn
{
    [Flags]
    internal enum MethodFlag
    {
        NotFound = 0,
        AutoGenerated = 1,
        RpcAndRpcManual = 2,
        Rpc = 4,
        RpcManual = 8,
        OnConnectedAndOnDisconnected = 16,
        OnConnected = 32,
        OnDisconnected = 64,
        OnErrored = 128,
        OnReceived = 256
    }
}